name: Banking API Test Framework

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'   # run when any workflow file changes
      - 'BankingAPIAutomation/**'   # Run only when BankingAPIAutomation files change
  pull_request:
    branches: [ "master" ]
    paths:
      - 'BankingAPIAutomation/**'
  schedule:
    - cron: '30 18 * * *'  # Daily at 11:30 PM IST (6:00 PM UTC)
    - cron: '05 3 * * *'   # Daily at 8:35 AM IST (3:05 AM UTC)
  workflow_dispatch:        # Allow manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    defaults:
      run:
        working-directory: BankingAPIAutomation   # Set BankingAPIAutomation as working dir

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Execute Banking API Tests
      run: mvn clean test -Dsuite=suite -X

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Logs
        path: BankingAPIAutomation/logs/

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: BankingAPIAutomation/target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
