name: API Test Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
schedule:
    # Runs twice: daily at 2 AM UTC and Monday/Thursday at 2 PM UTC
    - cron: '0 2 * * *'     # Daily at 2 AM UTC
    - cron: '0 14 * * 1,4'  # Monday and Thursday at 2 PM UTC
 # workflow_dispatch:  # Allows manual trigger from GitHub UI
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Execute Test
      run: mvn clean test -Dsuite=suite -X
- name: Upload a Build Artifact
uses: actions/upload-artifact@v4.6.2
with:
name:Logs
     path: logs/

     -name: Publish Test Report
     if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
